const anda = [10, 20, 30, 40, 50, 60, 70, 80];
const team = ["sakib", "shetab", "aksah", "ohi", "mehedi hasan"];
// team[3] = "Asif";
team[team.length] = "asif aman";
const arr = [];
arr[0] = 1;
arr[1] = 2;
arr[2] = 3;
arr[99] = 100;
console.log(arr);
console.log(team, anda.length);
